# Generated by Django 4.2.4 on 2023-10-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureproduct',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
