# Generated by Django 4.2.4 on 2023-08-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureproduct',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/'),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
