# Generated by Django 4.2.4 on 2023-08-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnitureproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
