# Generated by Django 4.2.4 on 2023-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0002_furnitureproduct_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureproduct',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
