# Generated by Django 4.2.4 on 2023-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0002_furnitureproduct_model_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureproduct',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
