# Generated by Django 5.2.5 on 2025-08-18 19:42

import furniturestore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniturestore', '0003_furnitureproduct_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=furniturestore.models.image_folder_path),
        ),
    ]
