# Generated by Django 5.2.5 on 2025-10-01 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furniturestore', '0004_alter_additionalimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contentgen/uploads/%Y/%m/%d/')),
                ('detected_category', models.CharField(blank=True, max_length=255)),
                ('features_json', models.JSONField(blank=True, default=dict)),
                ('seo_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('failed', 'Помилка')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_descriptions', to='furniturestore.furnitureproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
