# Generated by Django 5.2.5 on 2025-10-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentgen', '0001_initial'),
        ('furniturestore', '0004_alter_additionalimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddescription',
            options={},
        ),
        migrations.AddField(
            model_name='generateddescription',
            name='source',
            field=models.CharField(choices=[('OpenAI', 'OpenAI'), ('OpenRouter', 'OpenRouter'), ('Fallback', 'Заглушка'), ('None', 'Невідомо')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='generateddescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generateddescription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generateddescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gen_images/'),
        ),
        migrations.AlterField(
            model_name='generateddescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniturestore.furnitureproduct'),
        ),
        migrations.AlterField(
            model_name='generateddescription',
            name='seo_text',
            field=models.TextField(blank=True),
        ),
    ]
