# Generated by Django 4.2.4 on 2024-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customer_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
