# Generated by Django 4.2.4 on 2024-05-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
    ]
