# Generated by Django 5.2.5 on 2025-08-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_orderitem_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('processing', 'В обробці'), ('shipped', 'Відправлений'), ('delivered', 'Доставлений'), ('cancelled', 'Скасований')], default='new', max_length=20),
        ),
    ]
