# Generated by Django 5.2.5 on 2025-09-10 20:37

import cart.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_interaction_useractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('login', 'Вхід'), ('logout', 'Вихід'), ('order_created', 'Створення замовлення'), ('order_status_change', 'Зміна статусу замовлення'), ('bulk_order_action', 'Масова дія з замовленнями')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(default=cart.models.get_system_user_id, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
