# Generated by Django 5.2.5 on 2025-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_useractionlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
