# Generated by Django 5.2.5 on 2025-09-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_useractionlog_username'),
    ]

    operations = [
    ]
