# Generated by Django 5.2.5 on 2025-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20250911_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
